# Generated by Django 4.0 on 2021-12-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctapi', '0002_foster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('NONE', 'None'), ('GARAGE', 'Garage'), ('ADOPTCTR', 'AdoptCtr'), ('FOSTER', 'Foster')], default='NONE', max_length=8)),
                ('room_num', models.CharField(choices=[('NONE', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='NONE', max_length=8)),
                ('foster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats', to='ctapi.foster')),
            ],
            options={
                'verbose_name_plural': 'cats',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(max_length=100)),
                ('practice_name', models.CharField(max_length=100, unique=True)),
                ('phone_num', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'vets',
            },
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateField()),
                ('next_appt_date', models.DateField()),
                ('problem', models.TextField(blank=True, max_length=1024)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats', to='ctapi.cat')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vets', to='ctapi.vet')),
            ],
        ),
        migrations.AddField(
            model_name='vet',
            name='cats',
            field=models.ManyToManyField(related_name='vets', through='ctapi.VetVisit', to='ctapi.Cat'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescribed', models.DateField()),
                ('prescription_num', models.PositiveIntegerField(unique=True)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('instructions', models.CharField(blank=True, default='', max_length=512)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='ctapi.cat')),
                ('med', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='ctapi.medication')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='ctapi.vet')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='prescribed_by',
            field=models.ManyToManyField(related_name='medications', through='ctapi.Prescription', to='ctapi.Vet'),
        ),
        migrations.AddField(
            model_name='medication',
            name='prescribed_to',
            field=models.ManyToManyField(related_name='medications', through='ctapi.Prescription', to='ctapi.Cat'),
        ),
    ]
