# Generated by Django 4.0 on 2021-12-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctapi', '0004_alter_vet_practice_name_alter_vet_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
