version: '3.8'

services:
  ctapi:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on:
    - ctapi-db
  ctapi-db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ctapi
      - POSTGRES_PASSWORD=ctapi
      - POSTGRES_DB=ctapi_dev
volumes:
  postgres_data: